import { auth } from "@/lib/auth"; import { redirect } from "next/navigation"; import postgres from "postgres"; import { criarComodidade, editarComodidade, excluirComodidade } from "./actions"; import { CrudPage } from "@/components/admin/CrudPage";

export const dynamic = "force-dynamic";
export default async function ComodidadesPage({ searchParams }: { searchParams: Promise<{ erro?: string; ok?: string; editar?: string }> }) {
  const s=await auth(); if(!s?.user) redirect("/admin/login");
  const sp=await searchParams;
  const sql=postgres(process.env.DATABASE_URL!, {max:1, prepare: false }); const lista=await sql`SELECT * FROM comodidades ORDER BY ordem`; const pc=await sql`SELECT comodidade_id FROM pousada_comodidades`; const temNaPousada=new Set(pc.map((r:any)=>r.comodidade_id)); await sql.end();
  const ed=sp.editar ? lista.find((c:any)=>c.id===sp.editar) : null;
  const ff=ed?[{name:"id",type:"hidden",defaultValue:ed.id},{name:"nome",label:"Nome",required:true,defaultValue:ed.nome},{name:"slug",label:"Slug",required:true,defaultValue:ed.slug},{name:"icone",label:"Ícone",defaultValue:ed.icone??"check"},{name:"escopo",label:"Escopo",type:"select",defaultValue:ed.escopo??"quarto",options:[{value:"quarto",label:"Das suítes"},{value:"pousada",label:"Da pousada"}]},{name:"ordem",label:"Ordem",type:"number",defaultValue:ed.ordem},{name:"pousada_tem",label:"A pousada oferece (aparece no site e para a Marina)",type:"checkbox",defaultValue:temNaPousada.has(ed.id)?1:0},{name:"ativo",label:"Ativa",type:"checkbox",defaultValue:ed.ativo?1:0}]:[{name:"nome",label:"Nome",required:true},{name:"slug",label:"Slug",required:true},{name:"icone",label:"Ícone",defaultValue:"check"},{name:"escopo",label:"Escopo",type:"select",defaultValue:"quarto",options:[{value:"quarto",label:"Das suítes"},{value:"pousada",label:"Da pousada"}]},{name:"ordem",label:"Ordem",type:"number",defaultValue:0},{name:"pousada_tem",label:"A pousada oferece (aparece no site e para a Marina)",type:"checkbox",defaultValue:0}];
  return <CrudPage title="Comodidades" subtitle="O que a pousada e as suítes oferecem. É com esta lista que a Marina responde “tem ar-condicionado?”." lista={lista} columns={["nome","slug","escopo","ativo"]} fields={ff} criarAction={criarComodidade} editarAction={editarComodidade} excluirAction={excluirComodidade} editId={sp.editar} erro={sp.erro} ok={sp.ok} basePath="/admin/comodidades" />;
}